# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oracle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oracle.proto',
  package='oracle_communication',
  serialized_pb=_b('\n\x0coracle.proto\x12\x14oracle_communication\"\xd2\x01\n\rActionRequest\x12\x18\n\x10robot_relative_x\x18\x01 \x02(\x02\x12\x18\n\x10robot_relative_y\x18\x02 \x02(\x02\x12\x15\n\rrobot_radians\x18\x03 \x02(\x02\x12\x16\n\x0eobject_radians\x18\x04 \x02(\x02\x12\x1f\n\x17object_relative_x_prime\x18\x05 \x02(\x02\x12\x1f\n\x17object_relative_y_prime\x18\x06 \x02(\x02\x12\x1c\n\x14object_radians_prime\x18\x07 \x02(\x02\"?\n\x0e\x41\x63tionResponse\x12\n\n\x02\x64x\x18\x01 \x02(\x02\x12\n\n\x02\x64y\x18\x02 \x02(\x02\x12\n\n\x02\x64r\x18\x03 \x02(\x02\x12\t\n\x01t\x18\x04 \x02(\x02\"\xd7\x01\n\x12\x46\x65\x61sibilityRequest\x12\x18\n\x10robot_relative_x\x18\x01 \x02(\x02\x12\x18\n\x10robot_relative_y\x18\x02 \x02(\x02\x12\x15\n\rrobot_radians\x18\x03 \x02(\x02\x12\x16\n\x0eobject_radians\x18\x04 \x02(\x02\x12\x1f\n\x17object_relative_x_prime\x18\x05 \x02(\x02\x12\x1f\n\x17object_relative_y_prime\x18\x06 \x02(\x02\x12\x1c\n\x14object_radians_prime\x18\x07 \x02(\x02\"*\n\x13\x46\x65\x61sibilityResponse\x12\x13\n\x0bmahalanobis\x18\x01 \x02(\x02\"\x92\x01\n\x18\x46\x65\x61sibilitySampleRequest\x12\x16\n\x0eobject_radians\x18\x01 \x02(\x02\x12\x1f\n\x17object_relative_x_prime\x18\x02 \x02(\x02\x12\x1f\n\x17object_relative_y_prime\x18\x03 \x02(\x02\x12\x1c\n\x14object_radians_prime\x18\x04 \x02(\x02\"f\n\x19\x46\x65\x61sibilitySampleResponse\x12\x18\n\x10robot_relative_x\x18\x01 \x02(\x02\x12\x18\n\x10robot_relative_y\x18\x02 \x02(\x02\x12\x15\n\rrobot_radians\x18\x03 \x02(\x02\"\x8c\x01\n\x12PushabilityRequest\x12\x16\n\x0eobject_radians\x18\x04 \x02(\x02\x12\x1f\n\x17object_relative_x_prime\x18\x05 \x02(\x02\x12\x1f\n\x17object_relative_y_prime\x18\x06 \x02(\x02\x12\x1c\n\x14object_radians_prime\x18\x07 \x02(\x02\"*\n\x13PushabilityResponse\x12\x13\n\x0bmahalanobis\x18\x01 \x02(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ACTIONREQUEST = _descriptor.Descriptor(
  name='ActionRequest',
  full_name='oracle_communication.ActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_relative_x', full_name='oracle_communication.ActionRequest.robot_relative_x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='robot_relative_y', full_name='oracle_communication.ActionRequest.robot_relative_y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='robot_radians', full_name='oracle_communication.ActionRequest.robot_radians', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_radians', full_name='oracle_communication.ActionRequest.object_radians', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_relative_x_prime', full_name='oracle_communication.ActionRequest.object_relative_x_prime', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_relative_y_prime', full_name='oracle_communication.ActionRequest.object_relative_y_prime', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_radians_prime', full_name='oracle_communication.ActionRequest.object_radians_prime', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=249,
)


_ACTIONRESPONSE = _descriptor.Descriptor(
  name='ActionResponse',
  full_name='oracle_communication.ActionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dx', full_name='oracle_communication.ActionResponse.dx', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dy', full_name='oracle_communication.ActionResponse.dy', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dr', full_name='oracle_communication.ActionResponse.dr', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='t', full_name='oracle_communication.ActionResponse.t', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=314,
)


_FEASIBILITYREQUEST = _descriptor.Descriptor(
  name='FeasibilityRequest',
  full_name='oracle_communication.FeasibilityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_relative_x', full_name='oracle_communication.FeasibilityRequest.robot_relative_x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='robot_relative_y', full_name='oracle_communication.FeasibilityRequest.robot_relative_y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='robot_radians', full_name='oracle_communication.FeasibilityRequest.robot_radians', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_radians', full_name='oracle_communication.FeasibilityRequest.object_radians', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_relative_x_prime', full_name='oracle_communication.FeasibilityRequest.object_relative_x_prime', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_relative_y_prime', full_name='oracle_communication.FeasibilityRequest.object_relative_y_prime', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_radians_prime', full_name='oracle_communication.FeasibilityRequest.object_radians_prime', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=532,
)


_FEASIBILITYRESPONSE = _descriptor.Descriptor(
  name='FeasibilityResponse',
  full_name='oracle_communication.FeasibilityResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mahalanobis', full_name='oracle_communication.FeasibilityResponse.mahalanobis', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=534,
  serialized_end=576,
)


_FEASIBILITYSAMPLEREQUEST = _descriptor.Descriptor(
  name='FeasibilitySampleRequest',
  full_name='oracle_communication.FeasibilitySampleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_radians', full_name='oracle_communication.FeasibilitySampleRequest.object_radians', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_relative_x_prime', full_name='oracle_communication.FeasibilitySampleRequest.object_relative_x_prime', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_relative_y_prime', full_name='oracle_communication.FeasibilitySampleRequest.object_relative_y_prime', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_radians_prime', full_name='oracle_communication.FeasibilitySampleRequest.object_radians_prime', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=579,
  serialized_end=725,
)


_FEASIBILITYSAMPLERESPONSE = _descriptor.Descriptor(
  name='FeasibilitySampleResponse',
  full_name='oracle_communication.FeasibilitySampleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_relative_x', full_name='oracle_communication.FeasibilitySampleResponse.robot_relative_x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='robot_relative_y', full_name='oracle_communication.FeasibilitySampleResponse.robot_relative_y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='robot_radians', full_name='oracle_communication.FeasibilitySampleResponse.robot_radians', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=727,
  serialized_end=829,
)


_PUSHABILITYREQUEST = _descriptor.Descriptor(
  name='PushabilityRequest',
  full_name='oracle_communication.PushabilityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_radians', full_name='oracle_communication.PushabilityRequest.object_radians', index=0,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_relative_x_prime', full_name='oracle_communication.PushabilityRequest.object_relative_x_prime', index=1,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_relative_y_prime', full_name='oracle_communication.PushabilityRequest.object_relative_y_prime', index=2,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_radians_prime', full_name='oracle_communication.PushabilityRequest.object_radians_prime', index=3,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=832,
  serialized_end=972,
)


_PUSHABILITYRESPONSE = _descriptor.Descriptor(
  name='PushabilityResponse',
  full_name='oracle_communication.PushabilityResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mahalanobis', full_name='oracle_communication.PushabilityResponse.mahalanobis', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=974,
  serialized_end=1016,
)

DESCRIPTOR.message_types_by_name['ActionRequest'] = _ACTIONREQUEST
DESCRIPTOR.message_types_by_name['ActionResponse'] = _ACTIONRESPONSE
DESCRIPTOR.message_types_by_name['FeasibilityRequest'] = _FEASIBILITYREQUEST
DESCRIPTOR.message_types_by_name['FeasibilityResponse'] = _FEASIBILITYRESPONSE
DESCRIPTOR.message_types_by_name['FeasibilitySampleRequest'] = _FEASIBILITYSAMPLEREQUEST
DESCRIPTOR.message_types_by_name['FeasibilitySampleResponse'] = _FEASIBILITYSAMPLERESPONSE
DESCRIPTOR.message_types_by_name['PushabilityRequest'] = _PUSHABILITYREQUEST
DESCRIPTOR.message_types_by_name['PushabilityResponse'] = _PUSHABILITYRESPONSE

ActionRequest = _reflection.GeneratedProtocolMessageType('ActionRequest', (_message.Message,), dict(
  DESCRIPTOR = _ACTIONREQUEST,
  __module__ = 'oracle_pb2'
  # @@protoc_insertion_point(class_scope:oracle_communication.ActionRequest)
  ))
_sym_db.RegisterMessage(ActionRequest)

ActionResponse = _reflection.GeneratedProtocolMessageType('ActionResponse', (_message.Message,), dict(
  DESCRIPTOR = _ACTIONRESPONSE,
  __module__ = 'oracle_pb2'
  # @@protoc_insertion_point(class_scope:oracle_communication.ActionResponse)
  ))
_sym_db.RegisterMessage(ActionResponse)

FeasibilityRequest = _reflection.GeneratedProtocolMessageType('FeasibilityRequest', (_message.Message,), dict(
  DESCRIPTOR = _FEASIBILITYREQUEST,
  __module__ = 'oracle_pb2'
  # @@protoc_insertion_point(class_scope:oracle_communication.FeasibilityRequest)
  ))
_sym_db.RegisterMessage(FeasibilityRequest)

FeasibilityResponse = _reflection.GeneratedProtocolMessageType('FeasibilityResponse', (_message.Message,), dict(
  DESCRIPTOR = _FEASIBILITYRESPONSE,
  __module__ = 'oracle_pb2'
  # @@protoc_insertion_point(class_scope:oracle_communication.FeasibilityResponse)
  ))
_sym_db.RegisterMessage(FeasibilityResponse)

FeasibilitySampleRequest = _reflection.GeneratedProtocolMessageType('FeasibilitySampleRequest', (_message.Message,), dict(
  DESCRIPTOR = _FEASIBILITYSAMPLEREQUEST,
  __module__ = 'oracle_pb2'
  # @@protoc_insertion_point(class_scope:oracle_communication.FeasibilitySampleRequest)
  ))
_sym_db.RegisterMessage(FeasibilitySampleRequest)

FeasibilitySampleResponse = _reflection.GeneratedProtocolMessageType('FeasibilitySampleResponse', (_message.Message,), dict(
  DESCRIPTOR = _FEASIBILITYSAMPLERESPONSE,
  __module__ = 'oracle_pb2'
  # @@protoc_insertion_point(class_scope:oracle_communication.FeasibilitySampleResponse)
  ))
_sym_db.RegisterMessage(FeasibilitySampleResponse)

PushabilityRequest = _reflection.GeneratedProtocolMessageType('PushabilityRequest', (_message.Message,), dict(
  DESCRIPTOR = _PUSHABILITYREQUEST,
  __module__ = 'oracle_pb2'
  # @@protoc_insertion_point(class_scope:oracle_communication.PushabilityRequest)
  ))
_sym_db.RegisterMessage(PushabilityRequest)

PushabilityResponse = _reflection.GeneratedProtocolMessageType('PushabilityResponse', (_message.Message,), dict(
  DESCRIPTOR = _PUSHABILITYRESPONSE,
  __module__ = 'oracle_pb2'
  # @@protoc_insertion_point(class_scope:oracle_communication.PushabilityResponse)
  ))
_sym_db.RegisterMessage(PushabilityResponse)


# @@protoc_insertion_point(module_scope)
